name: analyzer_cli
version: 0.0.1
description: Command line interface for the Dart Analyzer.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/analyzer_cli

environment:
  sdk: '>=1.0.0 <2.0.0'

