name: analyzer_cli
version: 1.0.1
description: Command line interface for the Dart Analyzer.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/analyzer_cli
dependencies:
  analyzer: '>=0.24.0 <0.26.0'
  args: '>=0.13.0 <0.14.0'
  linter: '>=0.0.2+1 <0.1.0'
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'

